/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Logica.MedicamentosLiquidos;
import Logica.MedicamentosSolidos;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author eljun
 */
public class Administrador_2 extends javax.swing.JFrame {

    /**
     * Creates new form Administrador_2
     */
    public Administrador_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanelMedSol = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtNomSol = new javax.swing.JTextField();
        txtCantSol = new javax.swing.JTextField();
        txtPreSol = new javax.swing.JTextField();
        txtPreCaj = new javax.swing.JTextField();
        txtCodLugSol = new javax.swing.JTextField();
        txtCodMedSol = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDesSol = new javax.swing.JTextArea();
        btnActualizar = new javax.swing.JButton();
        btnElim = new javax.swing.JButton();
        btnInser = new javax.swing.JButton();
        jPanelLiq = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNomLiq = new javax.swing.JTextField();
        txtCantLiq = new javax.swing.JTextField();
        txtPreLiqu = new javax.swing.JTextField();
        txtCodLugLiq = new javax.swing.JTextField();
        txtCodMedLiq = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDesLiq = new javax.swing.JTextArea();
        btnActuLiq = new javax.swing.JButton();
        btnElimLiq = new javax.swing.JButton();
        btnInseLiq = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jButton7.setText("jButton7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilities/Logo negro.png"))); // NOI18N
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilities/Fondo Consulta.png"))); // NOI18N
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(-154, -31, 670, 400));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 490, 340));

        jButton2.setText("Med. Solidos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jButton1.setText("Med. Liquidos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jPanelMedSol.setOpaque(false);
        jPanelMedSol.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Nombre");
        jPanelMedSol.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel11.setText("Cantidad");
        jPanelMedSol.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel12.setText("Precio Tableta");
        jPanelMedSol.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel13.setText("Precio Caja");
        jPanelMedSol.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel14.setText("Cod. Lugar");
        jPanelMedSol.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel15.setText("Cod. Med.");
        jPanelMedSol.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        jPanelMedSol.add(txtNomSol, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 18, 120, -1));
        jPanelMedSol.add(txtCantSol, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 48, 120, -1));

        txtPreSol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPreSolActionPerformed(evt);
            }
        });
        jPanelMedSol.add(txtPreSol, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 78, 120, -1));
        jPanelMedSol.add(txtPreCaj, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 108, 120, -1));
        jPanelMedSol.add(txtCodLugSol, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 138, 120, -1));
        jPanelMedSol.add(txtCodMedSol, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 168, 120, -1));

        jLabel16.setText("Descripción");
        jPanelMedSol.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        txtDesSol.setColumns(20);
        txtDesSol.setRows(5);
        jScrollPane4.setViewportView(txtDesSol);

        jPanelMedSol.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanelMedSol.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, 80));

        btnElim.setText("Eliminar");
        btnElim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimActionPerformed(evt);
            }
        });
        jPanelMedSol.add(btnElim, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 130, 70, 80));

        btnInser.setText("Insertar");
        btnInser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserActionPerformed(evt);
            }
        });
        jPanelMedSol.add(btnInser, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 70, 80));

        getContentPane().add(jPanelMedSol, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 490, 340));

        jPanelLiq.setOpaque(false);
        jPanelLiq.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Nombre");
        jPanelLiq.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel5.setText("Cantidad");
        jPanelLiq.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel6.setText("Precio");
        jPanelLiq.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel7.setText("Cod. Lugar");
        jPanelLiq.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel8.setText("Cod. Med");
        jPanelLiq.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        txtNomLiq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomLiqActionPerformed(evt);
            }
        });
        jPanelLiq.add(txtNomLiq, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 17, 130, -1));
        jPanelLiq.add(txtCantLiq, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 57, 130, -1));
        jPanelLiq.add(txtPreLiqu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 97, 130, -1));
        jPanelLiq.add(txtCodLugLiq, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 137, 130, -1));
        jPanelLiq.add(txtCodMedLiq, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 177, 130, -1));

        jLabel9.setText("Descripción");
        jPanelLiq.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        txtDesLiq.setColumns(20);
        txtDesLiq.setRows(5);
        jScrollPane2.setViewportView(txtDesLiq);

        jPanelLiq.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        btnActuLiq.setText("Actualizar");
        btnActuLiq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActuLiqActionPerformed(evt);
            }
        });
        jPanelLiq.add(btnActuLiq, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, 80));

        btnElimLiq.setText("Eliminar");
        btnElimLiq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimLiqActionPerformed(evt);
            }
        });
        jPanelLiq.add(btnElimLiq, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 130, 70, 80));

        btnInseLiq.setText("Insertar");
        btnInseLiq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInseLiqActionPerformed(evt);
            }
        });
        jPanelLiq.add(btnInseLiq, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 70, 80));

        getContentPane().add(jPanelLiq, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 490, 340));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilities/Logo.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilities/Lateral consulta.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -2, -1, 400));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilities/Fondo Consulta.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jPanel3.setVisible(false);
        jPanelMedSol.setVisible(true);
        jPanelLiq.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jPanel3.setVisible(false);
        jPanelMedSol.setVisible(false);
        jPanelLiq.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPreSolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPreSolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPreSolActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int codMedSol = Integer.parseInt(txtCodMedSol.getText());
        String nombreSol = txtNomSol.getText();
        String descripSol= txtDesSol.getText();
        int cantSol = Integer.parseInt(txtCantSol.getText());
        float preSol = Float.parseFloat(txtPreSol.getText());
        float preSolCaja = Float.parseFloat(txtPreSol.getText());
        int lugSol = Integer.parseInt(txtCodLugSol.getText());
        
        MedicamentosSolidos medsol = new MedicamentosSolidos();
        medsol.setCodigoMedSol(codMedSol);
        medsol.setNombre(nombreSol);
        medsol.setCantidad(cantSol);
        medsol.setCodigoLugSol(lugSol);
        medsol.setPrecio_caja(preSolCaja);
        medsol.setPrecio_tableta(preSol);
        medsol.setDescripcion(descripSol);
        JOptionPane.showMessageDialog(this, "El producto a sido guardado "+ medsol.toString());
        if(medsol.ActualizarSol()){
            JOptionPane.showMessageDialog(this, "Operacion ejecutada con exito");
        }
        else{
            JOptionPane.showMessageDialog(this, "Operacion fallida");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnInserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserActionPerformed
        String nombreSol = txtNomSol.getText();
        String descripSol= txtDesSol.getText();
        int cantSol = Integer.parseInt(txtCantSol.getText());
        float preSol = Float.parseFloat(txtPreSol.getText());
        float preSolCaja = Float.parseFloat(txtPreCaj.getText());
        int lugSol = Integer.parseInt(txtCodLugSol.getText());
        // TODO add your handling code here:
        MedicamentosSolidos medsol = new MedicamentosSolidos();
        medsol.setNombre(nombreSol);
        medsol.setCantidad(cantSol);
        medsol.setCodigoLugSol(lugSol);
        medsol.setPrecio_caja(preSolCaja);
        medsol.setPrecio_tableta(preSol);
        medsol.setDescripcion(descripSol);
        try {
            if(medsol.GuardaSol()){
                JOptionPane.showMessageDialog(this, "El producto a sido guardado "+ medsol.toString());
            }
            else{
                JOptionPane.showMessageDialog(this,"Error al guardar el producto");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Administrador_2.class.getName()).log(Level.SEVERE, null, ex);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnInserActionPerformed

    private void btnElimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimActionPerformed
        int codMedSol = Integer.parseInt(txtCodMedSol.getText());
        MedicamentosSolidos medsol = new MedicamentosSolidos();
        medsol.setCodigoMedSol(codMedSol);
        int opcion = JOptionPane.showConfirmDialog(null, "¿Quieres eliminar el producto?", "Eliminar", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(opcion==0){
            if(medsol.EliminarSol()){
                JOptionPane.showMessageDialog(this, "Operacion ejecutada con exito");
            }else{
                JOptionPane.showMessageDialog(this, "Operacion fallida");
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnElimActionPerformed

    private void txtNomLiqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomLiqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomLiqActionPerformed

    private void btnActuLiqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActuLiqActionPerformed
        int codMedLiq = Integer.parseInt(txtCodMedLiq.getText());
        String nombre = txtNomLiq.getText();
        String descripcion = txtDesLiq.getText();
        int cantidad = Integer.parseInt(txtCantLiq.getText());
        float precio = Float.parseFloat(txtPreLiqu.getText());
        int lugar = Integer.parseInt(txtCodLugLiq.getText());
        
        MedicamentosLiquidos medliq = new MedicamentosLiquidos();
        medliq.setCod_Liquidos(codMedLiq);
        medliq.setNombre(nombre);
        medliq.setCantidad_Frasco(cantidad);
        medliq.setDescripcion(descripcion);
        medliq.setPrecio_Frasco(precio);
        medliq.setCod_Lugares(lugar);
        
        JOptionPane.showMessageDialog(this, "El producto a sido guardado "+ medliq.toString());
        if(medliq.ActualizarLiq()){
            JOptionPane.showMessageDialog(this, "Operacion ejecutada con exito");
        }
        else{
            JOptionPane.showMessageDialog(this, "Operacion fallida");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnActuLiqActionPerformed

    private void btnElimLiqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimLiqActionPerformed
        int codMedLiq = Integer.parseInt(txtCodMedLiq.getText());
        
        MedicamentosLiquidos medliq = new MedicamentosLiquidos();
        medliq.setCod_Liquidos(codMedLiq);
        int opcion = JOptionPane.showConfirmDialog(null, "¿Quieres eliminar el producto?", "Eliminar", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(opcion==0){
            if(medliq.EliminarLiq()){
                JOptionPane.showMessageDialog(this, "Operacion ejecutada con exito");
            }else{
                JOptionPane.showMessageDialog(this, "Operacion fallida");
            }
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnElimLiqActionPerformed

    private void btnInseLiqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInseLiqActionPerformed
        String nombre = txtNomLiq.getText();
        String descripcion = txtDesSol.getText();
        int cantidad = Integer.parseInt(txtCantSol.getText());
        float precio = Float.parseFloat(txtPreLiqu.getText());
        int lugar = Integer.parseInt(txtCodLugLiq.getText());
        
        MedicamentosLiquidos medliq = new MedicamentosLiquidos();
        medliq.setNombre(nombre);
        medliq.setCantidad_Frasco(cantidad);
        medliq.setDescripcion(descripcion);
        medliq.setPrecio_Frasco(precio);
        medliq.setCod_Lugares(lugar);
        
        try {
            if(medliq.GuardarLiq()){
                JOptionPane.showMessageDialog(this, "El producto a sido guardado "+ medliq.toString());
            }
            else{
                JOptionPane.showMessageDialog(this,"Error al guardar el producto");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Administrador_2.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInseLiqActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActuLiq;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnElim;
    private javax.swing.JButton btnElimLiq;
    private javax.swing.JButton btnInseLiq;
    private javax.swing.JButton btnInser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelLiq;
    private javax.swing.JPanel jPanelMedSol;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField txtCantLiq;
    private javax.swing.JTextField txtCantSol;
    private javax.swing.JTextField txtCodLugLiq;
    private javax.swing.JTextField txtCodLugSol;
    private javax.swing.JTextField txtCodMedLiq;
    private javax.swing.JTextField txtCodMedSol;
    private javax.swing.JTextArea txtDesLiq;
    private javax.swing.JTextArea txtDesSol;
    private javax.swing.JTextField txtNomLiq;
    private javax.swing.JTextField txtNomSol;
    private javax.swing.JTextField txtPreCaj;
    private javax.swing.JTextField txtPreLiqu;
    private javax.swing.JTextField txtPreSol;
    // End of variables declaration//GEN-END:variables
}
