/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Logica.Administradores;
import Logica.ConexionBD;
import Logica.Lugares;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eljun
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1Admin = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCodAdmin = new javax.swing.JTextField();
        txtCodLugAdm = new javax.swing.JTextField();
        txtNomAdm = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtTipDoc = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtTelMov = new javax.swing.JTextField();
        btnConAdm = new javax.swing.JButton();
        btnInsAdm = new javax.swing.JButton();
        btnActAdm = new javax.swing.JButton();
        btnEliAdm = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtNumDoc = new javax.swing.JTextField();
        jPanel2Lug = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtCodLug = new javax.swing.JTextField();
        txtCodNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelFij = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnConsulta = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        setLocation(new java.awt.Point(545, 250));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1Admin.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1Admin.setAutoscrolls(true);
        jPanel1Admin.setOpaque(false);
        jPanel1Admin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cod admin");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1Admin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 70, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo Admin", "Nombre", "Apellido", "Tipo Doc", "Num Doc", "Correo", "Tel Movil", "Codigo Lugar"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1Admin.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 140));

        jLabel5.setText("Cod lugar");
        jPanel1Admin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 60, -1));

        jLabel6.setText("Nombre");
        jPanel1Admin.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 60, -1));

        jLabel7.setText("Apellido");
        jPanel1Admin.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 60, -1));

        jLabel8.setText("Tipo doc");
        jPanel1Admin.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 60, -1));

        jLabel9.setText("Correo");
        jPanel1Admin.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 60, -1));

        jLabel10.setText("Tel movil");
        jPanel1Admin.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 60, -1));
        jPanel1Admin.add(txtCodAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 170, -1));
        jPanel1Admin.add(txtCodLugAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 170, -1));
        jPanel1Admin.add(txtNomAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 170, -1));
        jPanel1Admin.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 170, -1));
        jPanel1Admin.add(txtTipDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 170, -1));
        jPanel1Admin.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 170, -1));
        jPanel1Admin.add(txtTelMov, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 170, -1));

        btnConAdm.setText("Consulta");
        btnConAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConAdmActionPerformed(evt);
            }
        });
        jPanel1Admin.add(btnConAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 110, 70));

        btnInsAdm.setText("Insertar");
        btnInsAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsAdmActionPerformed(evt);
            }
        });
        jPanel1Admin.add(btnInsAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 110, 70));

        btnActAdm.setText("Actualizar");
        btnActAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActAdmActionPerformed(evt);
            }
        });
        jPanel1Admin.add(btnActAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 110, 70));

        btnEliAdm.setText("Eliminar");
        btnEliAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliAdmActionPerformed(evt);
            }
        });
        jPanel1Admin.add(btnEliAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 110, 70));

        jLabel15.setText("Num doc");
        jPanel1Admin.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));
        jPanel1Admin.add(txtNumDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 170, -1));

        getContentPane().add(jPanel1Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 490, 310));

        jPanel2Lug.setOpaque(false);
        jPanel2Lug.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Dirección", "Tel fijo"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jPanel2Lug.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 470, 140));

        jLabel11.setText("Codigo");
        jPanel2Lug.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel12.setText("Nombre");
        jPanel2Lug.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel13.setText("Dirección");
        jPanel2Lug.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel14.setText("Tel. Fijo");
        jPanel2Lug.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));
        jPanel2Lug.add(txtCodLug, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 170, -1));
        jPanel2Lug.add(txtCodNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 170, -1));
        jPanel2Lug.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 170, -1));
        jPanel2Lug.add(txtTelFij, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 170, -1));

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        jPanel2Lug.add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 110, 70));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2Lug.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 110, 70));

        btnConsulta.setText("Consulta");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });
        jPanel2Lug.add(btnConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 110, 70));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel2Lug.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 110, 70));

        getContentPane().add(jPanel2Lug, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 490, 310));

        jButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilities/Boton lugares B.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 130, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilities/Boton admin B.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 130, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilities/Logo.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilities/Lateral consulta.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilities/Fondo Consulta.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setAutoscrolls(true);
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jPanel2Lug.setVisible(true);
        jPanel1Admin.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnEliAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliAdmActionPerformed
        int codAdm = Integer.parseInt(txtCodAdmin.getText());
        Administradores adms= new Administradores();
        adms.setCodAdmin(codAdm);
        int opcion = JOptionPane.showConfirmDialog(null, "¿Quieres eliminar el producto?", "Eliminar", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(opcion==0){
            if(adms.EliminarAdmins()){
                JOptionPane.showMessageDialog(this, "Operacion ejecutada con exito");
            }else{
                JOptionPane.showMessageDialog(this, "Operacion fallida");
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliAdmActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jPanel2Lug.setVisible(false);
        jPanel1Admin.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        Object[][] rowData = new Object[1][4];
        Object[] columnsNames={"Codigo","Nombre","Dirección","Tel fijo"};
        DefaultTableModel model= new DefaultTableModel();
        model.setColumnIdentifiers(columnsNames);
        jTable2.setModel(model);
        
        Lugares lu = new Lugares();
        List<Lugares> lista = lu.listarTodLugares();
        for(Lugares lug : lista){
            rowData[0][0]=lug.getCodLugares();
            rowData[0][1]=lug.getNombre();
            rowData[0][2]=lug.getDireccion();
            rowData[0][3]=lug.getTel_Fijo();
            model.addRow(rowData[0]);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultaActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        String nombre = txtCodNombre.getText();
        String direccion = txtDireccion.getText();
        int telFij = Integer.parseInt(txtTelFij.getText());
        
        Lugares lug= new Lugares();
        lug.setNombre(nombre);
        lug.setDireccion(direccion);
        lug.setTel_Fijo(telFij);
        if (lug.GuardarLugar()) {
            JOptionPane.showMessageDialog(this, "El producto a sido guardado "+ lug.toString());
        } else {
            JOptionPane.showMessageDialog(this,"Error al guardar el producto");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        String nombre = txtCodNombre.getText();
        String direccion = txtDireccion.getText();
        int telFij = Integer.parseInt(txtTelFij.getText());
        int codLug= Integer.parseInt(txtCodLug.getText());
        Lugares lug= new Lugares();
        lug.setCodLugares(codLug);
        lug.setNombre(nombre);
        lug.setDireccion(direccion);
        lug.setTel_Fijo(telFij);
        JOptionPane.showMessageDialog(this, "El lugar a sido guardado "+ lug.toString());
        if(lug.ActualizarLugar()){
            JOptionPane.showMessageDialog(this, "Operacion ejecutada con exito");
        }
        else{
            JOptionPane.showMessageDialog(this, "Operacion fallida");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int codLug= Integer.parseInt(txtCodLug.getText());
        Lugares lug= new Lugares();
        lug.setCodLugares(codLug);
        int opcion = JOptionPane.showConfirmDialog(null, "¿Quieres eliminar el producto?", "Eliminar", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(opcion==0){
            if(lug.EliminarLug()){
                JOptionPane.showMessageDialog(this, "Operacion ejecutada con exito");
            }else{
                JOptionPane.showMessageDialog(this, "Operacion fallida");
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnConAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConAdmActionPerformed
        Object[][] rowData = new Object[1][8];
        Object[] columnsNames={"Codigo Admin","Nombre","Apellido", "Tipo doc", "Num doc", "Correo", "Tel movil","Cod lugar"};
        DefaultTableModel model2= new DefaultTableModel();
        model2.setColumnIdentifiers(columnsNames);
        jTable1.setModel(model2);
        
        ConexionBD conex= new ConexionBD();
        Administradores adm = new Administradores();
        List<Administradores> lista = adm.listarTdsAdms();
        for(Administradores adms : lista){
            rowData[0][0]=adms.getCodAdmin();
            rowData[0][1]=adms.getNombre();
            rowData[0][2]=adms.getApellido();
            rowData[0][3]=adms.getTd();
            rowData[0][4]=adms.getNumDoc();
            rowData[0][5]=adms.getCorreo();
            rowData[0][6]=adms.getTelMovl();
            rowData[0][7]=adms.getCodLugares();
            model2.addRow(rowData[0]);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConAdmActionPerformed

    private void btnInsAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsAdmActionPerformed
         int codLug = Integer.parseInt(txtCodLug.getText());
        String nomAdm = txtNomAdm.getText();
        String apellido = txtApellido.getText();
        String td = txtTipDoc.getText();
        int numDoc= Integer.parseInt(txtNumDoc.getText());
        String correo = txtCorreo.getText();
        int telMovil= Integer.parseInt(txtTelMov.getText());
        
        Administradores adms = new Administradores();
        
        adms.setCodLugares(codLug);
        adms.setNombre(nomAdm);
        adms.setApellido(apellido);
        adms.setTd(td);
        adms.setNumDoc(numDoc);
        adms.setCorreo(correo);
        adms.setTelMovl(telMovil);
        if (adms.GuardarAdmins()) {
            JOptionPane.showMessageDialog(this, "El producto a sido guardado "+ adms.toString());
        } else {
            JOptionPane.showMessageDialog(this,"Error al guardar el producto");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnInsAdmActionPerformed

    private void btnActAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActAdmActionPerformed
       int codAdm = Integer.parseInt(txtCodAdmin.getText());
        int codLug = Integer.parseInt(txtCodLug.getText());
        String nomAdm = txtNomAdm.getText();
        String apellido = txtApellido.getText();
        String td = txtTipDoc.getText();
        int numDoc= Integer.parseInt(txtNumDoc.getText());
        String correo = txtCorreo.getText();
        int telMovil= Integer.parseInt(txtTelMov.getText());
        
        Administradores adms= new Administradores();
        adms.setCodAdmin(codAdm);
        adms.setCodLugares(codLug);
        adms.setNombre(nomAdm);
        adms.setApellido(apellido);
        adms.setTd(td);
        adms.setNumDoc(numDoc);
        adms.setCorreo(correo);
        adms.setTelMovl(telMovil);
        JOptionPane.showMessageDialog(this, "El lugar a sido guardado "+ adms.toString());
        if(adms.ActualizarAdmins()){
            JOptionPane.showMessageDialog(this, "Operacion ejecutada con exito");
        }
        else{
            JOptionPane.showMessageDialog(this, "Operacion fallida");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActAdmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActAdm;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnConAdm;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnEliAdm;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsAdm;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1Admin;
    private javax.swing.JPanel jPanel2Lug;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCodAdmin;
    private javax.swing.JTextField txtCodLug;
    private javax.swing.JTextField txtCodLugAdm;
    private javax.swing.JTextField txtCodNombre;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNomAdm;
    private javax.swing.JTextField txtNumDoc;
    private javax.swing.JTextField txtTelFij;
    private javax.swing.JTextField txtTelMov;
    private javax.swing.JTextField txtTipDoc;
    // End of variables declaration//GEN-END:variables
}
