/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Logica.ConexionBD;
import Logica.Lugares;
import Logica.MedicamentosLiquidos;
import Logica.MedicamentosSolidos;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eljun
 */
public class Consulta extends javax.swing.JFrame {

    /**
     * Creates new form Consulta
     */
    public Consulta() {
        initComponents();
        llenarCombo();
        llnrCombMed();
        llnrCombMedLiq();
    }

    private void llenarCombo() {
        conexion = new ConexionBD();
        //i= conexion.getI();
        conexion.llenarCombo();
        //conexion.comboCompra();
        for (String lugar: conexion.getLugares()){
            jComboBox1.addItem(lugar);
            jComboBox2.addItem(lugar);
        }
    }
    private void llenarTabla(){
       String item;
       item=conexion.getItem();
       item = String.valueOf(jComboBox1.getSelectedItem());
       conexion = new ConexionBD();
       conexion.llenarTabla(item);
       
       //sql2= "SELECT `Nombre`, `Descripcion`, `Cantidad`, `Precio_tableta`, `Precio_caja`, `Cod_solidos` FROM `tbl_medicamentos_solidos` WHERE `Cod_lugares` = 1";
       //sql3= "SELECT `Nombre`, `Descripcion`, `Cantidad_frasco`, `Precio_frasco`, `Cod_liquidos` FROM `tbl_medicamentos_liquidos` WHERE `Cod_lugares` = 1";
        
    }
    private void llenarTabla2(){
        String item2;
        conexion = new ConexionBD();
        item2=conexion.getItem();
        item2 = String.valueOf(jComboBox2.getSelectedItem());
        conexion = new ConexionBD();
        conexion.llenarTabla(item2);
    }
    private void llnrCombMed(){
        conexion = new ConexionBD();
        //i= conexion.getI();
        conexion.llenarCombMediSol();
        for (String lugar: conexion.getLugares()){
            jComboBox4.addItem(lugar);
            //jComboBox2.addItem(lugar);
        }
    }
    private void llnrCombMedLiq(){
        conexion = new ConexionBD();
        //i= conexion.getI();
        conexion.llenarCombMediLiq();
        for (String lugar: conexion.getLugares()){
            jComboBox3.addItem(lugar);
            //jComboBox2.addItem(lugar);
        }
    }
    private void llnrTabla(){
        String item3;
        conexion = new ConexionBD();
        item3=conexion.getItem();
        item3 = String.valueOf(jComboBox4.getSelectedItem());
        conexion = new ConexionBD();
        conexion.llnrTblMedSol(item3);
    }
    private void llnrTablaLiq(){
        String item4;
        conexion = new ConexionBD();
        item4=conexion.getItem();
        item4 = String.valueOf(jComboBox3.getSelectedItem());
        conexion = new ConexionBD();
        conexion.llnrTblMedLiq(item4);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Lugar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 90, -1));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setText("Consultar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 70, 70));

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 450, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 440, 190));

        jTabbedPane1.addTab("Medicamentos Solidos", jPanel1);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton8.setText("Consultar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 70, 70));

        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 450, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable3);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 440, 190));

        jTabbedPane1.addTab("Medicamentos Liquidos", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 540, 400));

        jButton2.setText("Medicamento");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 90, -1));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setText("Consultar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 70, 70));

        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 450, -1));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 440, 190));

        jTabbedPane2.addTab("Medicamentos Solidos", jPanel4);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setText("Consultar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 70, 70));

        jPanel3.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 450, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 170));

        jTabbedPane2.addTab("Medicamentos Liquidos", jPanel3);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 540, 390));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilities/Logo.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilities/Lateral consulta.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -2, -1, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTabbedPane1.setVisible(true);
        jTabbedPane2.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTabbedPane1.setVisible(false);
        jTabbedPane2.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        llenarTabla2();
        Object[][] liquidos = new Object[1][5];
        Object[] columnsNames={"Nombre","Descripción","Cantidad","Precio frasco", "Codigo"};
        DefaultTableModel model2 = new DefaultTableModel();
        model2.setColumnIdentifiers(columnsNames);
        jTable3.setModel(model2);
        MedicamentosLiquidos liquido = new MedicamentosLiquidos();
        List<MedicamentosLiquidos> lista = conexion.listarLiquidos();
        for (MedicamentosLiquidos liq : lista){
            liquidos[0][0]= liq.getNombre();
            liquidos[0][1]= liq.getDescripcion();
            liquidos[0][2] = liq.getCantidad_Frasco();
            liquidos[0][3]= liq.getPrecio_Frasco();
            liquidos[0][4]= liq.getCod_Liquidos();
            model2.addRow(liquidos[0]);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        System.out.println(conexion.getCodigo());
        llenarTabla();
        Object[][] solidos = new Object[1][6];
        Object[] columnsNames={"Nombre","Descripción","Cantidad","Precio tableta", "Precio caja", "Codigo"};
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columnsNames);
        jTable1.setModel(model);
        MedicamentosSolidos solido = new MedicamentosSolidos();
        List<MedicamentosSolidos> lista = conexion.listarSolidos();
        for (MedicamentosSolidos sol : lista){
            solidos[0][0]= sol.getNombre();
            System.out.println(sol.getNombre());
            solidos[0][1]= sol.getDescripcion();
            solidos[0][2] = sol.getCantidad();
            solidos[0][3]= sol.getPrecio_tableta();
            solidos[0][4]= sol.getPrecio_caja();
            solidos[0][5]= sol.getCodigoLugSol();
            model.addRow(solidos[0]);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        llnrTabla();
        String item3;
        item3=conexion.getItem();
        item3 = String.valueOf(jComboBox4.getSelectedItem());
        //conexion.nombSol(item);
        Object[][] places = new Object[1][3];
        Object[] columnsNames={"Nombre","Dirección","Telefono Fijo"};
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columnsNames);
        jTable4.setModel(model);
        Lugares lug = new Lugares();
        List<Lugares> lista = conexion.listarLugSol();
        for (Lugares pla : lista){
            places[0][0]= pla.getNombre();
            System.out.println(pla.getNombre());
            places[0][1]= pla.getDireccion();
            places[0][2] = pla.getTel_Fijo();
            model.addRow(places[0]);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        llnrTablaLiq();
        String item4;
        item4=conexion.getItem();
        item4=String.valueOf(jComboBox3.getSelectedItem());
        Object [][] places = new Object[1][4];
        Object[] columnsNames ={"Nombre","Dirección","Telefono Fijo"};
        DefaultTableModel model2 = new DefaultTableModel();
        model2.setColumnIdentifiers(columnsNames);
        jTable2.setModel(model2);
        Lugares lug = new Lugares();
        List <Lugares> lista2 = conexion.listarLugSol();
        for(Lugares pla:lista2){
            places[0][0]=pla.getNombre();
            places[0][1]=pla.getDireccion();
            places[0][2]=pla.getTel_Fijo();
            model2.addRow(places[0]);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
    Statement comando = null;
    ResultSet registros = null;
    ConexionBD conexion = null;
}
